all: SimpleShell SimpleScheduler  testf

SimpleShell: SimpleShell.c
	gcc -o SimpleShell SimpleShell.c

SimpleScheduler: SimpleScheduler.c
	gcc -o SimpleScheduler SimpleScheduler.c


testf: testf.c
	gcc -o testf testf.c


clean:
	rm -f SimpleShell SimpleScheduler  testf
